import type { Feature, Prompt, VibeSession } from "@/types";

export const sampleFeatures: Feature[] = [
  {
    id: "feat-001",
    title: "Carrier rate comparison",
    problemStatement:
      "Freight buyers spend 45+ minutes manually comparing rates from 8+ carriers. We need a unified view to cut that to under 5 minutes.",
    status: "BUILDING",
    size: "L",
    quarter: "Q2 2024",
    owner: "Sara Chen",
    jiraEpicId: "VF-101",
    aiSuggestedSize: "L",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-002",
    title: "Bulk shipment upload",
    problemStatement:
      "Operations teams import 200–500 shipments per day via CSV from legacy TMS. Manual entry causes errors and takes 3+ hours.",
    status: "DONE",
    size: "M",
    quarter: "Q1 2024",
    owner: "Marcus Webb",
    jiraEpicId: "VF-88",
    aiSuggestedSize: "M",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-003",
    title: "Dynamic pricing API",
    problemStatement:
      "Enterprise customers need real-time surcharge adjustments based on fuel index and lane volatility without re-negotiating contracts.",
    status: "SCOPING",
    size: "XL",
    quarter: "Q3 2024",
    owner: "Priya Nair",
    jiraEpicId: "VF-115",
    aiSuggestedSize: "XL",
    aiConfidence: "MEDIUM",
    aiAccepted: true,
  },
  {
    id: "feat-004",
    title: "CO2 emissions report",
    problemStatement:
      "Shippers need Scope 3 carbon data per lane and per shipment to meet EU CSRD reporting mandates by Q1 2025.",
    status: "PROTOTYPING",
    size: "M",
    quarter: "Q2 2024",
    owner: "Lena Hoffmann",
    jiraEpicId: "VF-99",
    prototypeUrl: "https://prototype.vibeflow.app/co2-report",
    aiSuggestedSize: "L",
    aiConfidence: "MEDIUM",
    aiAccepted: false,
  },
  {
    id: "feat-005",
    title: "Customs doc generator",
    problemStatement:
      "Cross-border shipments require HS codes, commercial invoices, and certificates of origin. Errors lead to customs delays averaging 2.4 days.",
    status: "IDEA",
    size: null,
    quarter: "Q3 2024",
    owner: "James Okafor",
    aiSuggestedSize: "L",
    aiConfidence: "LOW",
  },
  {
    id: "feat-006",
    title: "Real-time tracking webhooks",
    problemStatement:
      "Customers want push notifications to their WMS/ERP when shipment milestones occur. Currently polling our API every 15 minutes causing rate limit issues.",
    status: "BUILDING",
    size: "M",
    quarter: "Q2 2024",
    owner: "Sara Chen",
    jiraEpicId: "VF-107",
    aiSuggestedSize: "M",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-007",
    title: "Booking confirmation PDF",
    problemStatement:
      "Logistics coordinators need a branded, printable booking confirmation to attach to warehouse pick orders. Currently copy-pasting from the UI.",
    status: "DONE",
    size: "S",
    quarter: "Q1 2024",
    owner: "Marcus Webb",
    jiraEpicId: "VF-79",
    aiSuggestedSize: "S",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-008",
    title: "Multi-currency rate cards",
    problemStatement:
      "European customers pay in EUR, GBP, and CHF. All rates currently shown in USD, creating confusion and manual FX conversion work.",
    status: "SCOPING",
    size: "M",
    quarter: "Q2 2024",
    owner: "Priya Nair",
    aiSuggestedSize: "M",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-009",
    title: "Lane performance dashboard",
    problemStatement:
      "PMs and account managers lack visibility into on-time delivery rates, damage rates, and cost per lane to make carrier allocation decisions.",
    status: "PROTOTYPING",
    size: "L",
    quarter: "Q3 2024",
    owner: "Lena Hoffmann",
    prototypeUrl: "https://prototype.vibeflow.app/lane-perf",
    aiSuggestedSize: "L",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-010",
    title: "Carrier scorecard & SLA alerts",
    problemStatement:
      "Operations teams manually track carrier SLAs in spreadsheets. Breaches are caught days late, causing customer escalations.",
    status: "IDEA",
    size: null,
    quarter: "Q4 2024",
    owner: "James Okafor",
    aiSuggestedSize: "M",
    aiConfidence: "MEDIUM",
  },
  {
    id: "feat-011",
    title: "Spot quote request workflow",
    problemStatement:
      "Shippers needing one-off capacity send emails to 12+ carriers. Response aggregation is manual and takes 4–6 hours per RFQ.",
    status: "BUILDING",
    size: "L",
    quarter: "Q2 2024",
    owner: "Sara Chen",
    jiraEpicId: "VF-112",
    aiSuggestedSize: "XL",
    aiConfidence: "MEDIUM",
    aiAccepted: false,
  },
  {
    id: "feat-012",
    title: "Hazmat shipment compliance checker",
    problemStatement:
      "Customers shipping dangerous goods face rejections at booking due to missing UN numbers and packing group declarations.",
    status: "PARKED",
    size: "XL",
    quarter: "Q4 2024",
    owner: "Marcus Webb",
    aiSuggestedSize: "XL",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-013",
    title: "AI load optimisation suggestions",
    problemStatement:
      "Partial truckloads cost customers 20–35% more per unit. An AI assistant could suggest consolidation opportunities in real time.",
    status: "IDEA",
    size: null,
    quarter: "Q4 2024",
    owner: "Priya Nair",
    aiSuggestedSize: "XL",
    aiConfidence: "LOW",
  },
  {
    id: "feat-014",
    title: "Customer self-service invoice portal",
    problemStatement:
      "Finance teams at shipper companies submit 200+ billing disputes per month via email. A self-service portal would reduce support load by an estimated 60%.",
    status: "SCOPING",
    size: "L",
    quarter: "Q3 2024",
    owner: "Lena Hoffmann",
    jiraEpicId: "VF-118",
    aiSuggestedSize: "L",
    aiConfidence: "HIGH",
    aiAccepted: true,
  },
  {
    id: "feat-015",
    title: "Automated dwell time detection",
    problemStatement:
      "Containers sitting at port beyond free time incur demurrage charges averaging $850/day. Automated alerts when dwell exceeds threshold could save customers $2M+ annually.",
    status: "IDEA",
    size: null,
    quarter: "Q4 2024",
    owner: "James Okafor",
    aiSuggestedSize: "M",
    aiConfidence: "MEDIUM",
  },
];

export const samplePrompts: Prompt[] = [
  {
    id: "prompt-001",
    title: "Kanban board scaffold",
    body: "Build a drag-and-drop Kanban board using @dnd-kit/core with columns: IDEA, SCOPING, PROTOTYPING, BUILDING, DONE, PARKED. Each card shows title, owner avatar, size badge, and quarter tag. Use Tailwind CSS with a navy/blue enterprise color palette. Cards should be draggable between columns with smooth animations.",
    tool: "v0",
    outputType: "React component",
    quality: 5,
    tags: ["kanban", "dnd-kit", "board", "features"],
    version: 3,
    usedInFeatures: ["feat-001", "feat-006", "feat-011"],
  },
  {
    id: "prompt-002",
    title: "AI size estimator panel",
    body: "Create a slide-over panel that takes a feature's problem statement and title as input, then displays an AI-suggested t-shirt size (XS/S/M/L/XL) with confidence level (HIGH/MEDIUM/LOW) and a brief reasoning. Include Accept/Override buttons. Style with a purple AI accent color.",
    tool: "Claude",
    outputType: "React component + API route",
    quality: 4,
    tags: ["ai", "estimation", "panel", "sizing"],
    version: 2,
    usedInFeatures: ["feat-001", "feat-003", "feat-009"],
  },
  {
    id: "prompt-003",
    title: "Recharts lane performance chart",
    body: "Build a multi-series line chart using recharts showing on-time delivery %, damage rate %, and cost/kg trend over 12 months per carrier lane. Include a lane selector dropdown, custom tooltip, and a reference line at 95% OTD threshold. Use a clean white card with subtle border.",
    tool: "Cursor",
    outputType: "React component",
    quality: 5,
    tags: ["recharts", "charts", "analytics", "lane"],
    version: 1,
    usedInFeatures: ["feat-009"],
  },
  {
    id: "prompt-004",
    title: "CSV bulk upload with validation",
    body: "Implement a drag-and-drop CSV upload component that validates required columns (reference, origin, destination, weight_kg, carrier), shows a preview table of the first 10 rows with error highlighting for invalid cells, and returns a JSON array ready for API submission. Use React with TypeScript and Zod for validation.",
    tool: "Cursor",
    outputType: "React component + Zod schema",
    quality: 5,
    tags: ["upload", "csv", "validation", "bulk"],
    version: 2,
    usedInFeatures: ["feat-002"],
  },
  {
    id: "prompt-005",
    title: "Multi-currency rate card table",
    body: "Create a sortable data table for freight rate cards with columns: lane, carrier, base rate, fuel surcharge, total, and currency selector (USD/EUR/GBP/CHF). Live FX conversion should update all values when currency changes. Use TanStack Table with Tailwind styling.",
    tool: "v0",
    outputType: "React component",
    quality: 4,
    tags: ["table", "currency", "rates", "fx"],
    version: 1,
    usedInFeatures: ["feat-008"],
  },
  {
    id: "prompt-006",
    title: "Webhook event log viewer",
    body: "Design a real-time event log component that shows incoming webhook events with status (delivered/failed/retrying), timestamp, event type, and payload preview. Include retry button for failed events and a filter bar for event types. Style as a terminal-like dark panel inside a light page.",
    tool: "Bolt",
    outputType: "React component",
    quality: 3,
    tags: ["webhooks", "events", "log", "tracking"],
    version: 1,
    usedInFeatures: ["feat-006"],
  },
  {
    id: "prompt-007",
    title: "CO2 emissions breakdown card",
    body: "Build a summary card showing CO2e kg per shipment broken down by transport mode (road, sea, air, rail). Include a donut chart, comparison vs industry average, and a color-coded badge (green/amber/red) based on intensity threshold. Data props should accept an array of mode+emissions objects.",
    tool: "ChatGPT",
    outputType: "React component",
    quality: 4,
    tags: ["co2", "sustainability", "chart", "emissions"],
    version: 2,
    usedInFeatures: ["feat-004"],
  },
  {
    id: "prompt-008",
    title: "Spot quote RFQ email template",
    body: "Generate a professional spot quote request email template for freight RFQs. Include: shipment details table, required carrier response fields, SLA terms, contact info placeholder. Output as both plain text and HTML. Tone should be professional but concise — logistics ops managers are busy.",
    tool: "Claude",
    outputType: "Email template (HTML + text)",
    quality: 4,
    tags: ["email", "rfq", "spot-quote", "template"],
    version: 1,
    usedInFeatures: ["feat-011"],
  },
  {
    id: "prompt-009",
    title: "Demurrage alert Slack integration",
    body: "Write a Next.js API route that receives a dwell time event webhook, calculates projected demurrage cost using a configurable rate schedule, and posts a formatted Slack Block Kit message to a specified channel. Include a suppress-for-24h button action handler.",
    tool: "Cursor",
    outputType: "API route + Slack Block Kit",
    quality: 5,
    tags: ["slack", "demurrage", "webhooks", "alerts"],
    version: 1,
    usedInFeatures: ["feat-015"],
  },
];

export const sampleVibeSessions: VibeSession[] = [
  {
    id: "session-001",
    title: "Carrier Rate Comparison — v1 prototype",
    date: "2024-03-12",
    duration: 120,
    status: "OPEN" as const,
    goal: "Build a working prototype of the rate comparison table with mock carrier data and basic filtering by lane.",
    linkedFeatureIds: ["feat-001"],
    promptIds: ["prompt-001"],
    prototypeUrl: "https://prototype.vibeflow.app/rate-compare-v1",
    notes: {
      worked:
        "v0 generated the table scaffold in under 10 minutes. DnD sorting worked first try. Tailwind classes were clean.",
      improve:
        "v0 struggled with complex multi-header table. Had to manually add sticky column logic. Need a better prompt for complex tables.",
    },
    backlogItems: [
      { id: "bl-001", title: "Add carrier logo column", status: "TODO" },
      { id: "bl-002", title: "Filter by carrier type (FTL/LTL)", status: "TODO" },
      {
        id: "bl-003",
        title: "Export filtered results to CSV",
        status: "IN_PROGRESS",
        jiraId: "VF-103",
      },
    ],
    jiraSyncedIds: ["VF-103"],
  },
  {
    id: "session-002",
    title: "CO2 Report — emissions card prototype",
    date: "2024-03-19",
    duration: 90,
    status: "CLOSED" as const,
    goal: "Prototype the per-shipment CO2e breakdown card and validate data model with the sustainability team.",
    linkedFeatureIds: ["feat-004"],
    promptIds: ["prompt-007"],
    prototypeUrl: "https://prototype.vibeflow.app/co2-card-v1",
    notes: {
      worked:
        "Donut chart worked well. Recharts donut renders cleanly with custom labels. Sustainability team approved the data structure.",
      improve:
        "ChatGPT prompt produced slightly off color values. Should use Claude for design-sensitive components next time.",
    },
    backlogItems: [
      {
        id: "bl-004",
        title: "Integrate with actual GLEC framework calculation",
        status: "TODO",
      },
      {
        id: "bl-005",
        title: "Add historical trend sparkline",
        status: "TODO",
      },
    ],
    jiraSyncedIds: [],
  },
  {
    id: "session-003",
    title: "Bulk Upload — CSV parser + validation UI",
    date: "2024-02-28",
    duration: 150,
    status: "CLOSED" as const,
    goal: "Build the end-to-end CSV upload flow: drag-and-drop, column validation, error preview, and POST to /api/shipments/bulk.",
    linkedFeatureIds: ["feat-002"],
    promptIds: ["prompt-004"],
    notes: {
      worked:
        "Zod schema generation from Cursor was excellent. Caught 6 edge cases I hadn't thought of. Error table highlighting looks professional.",
      improve:
        "File size limit handling wasn't included in the prompt output — had to add manually. Update prompt to include max-file-size prop.",
    },
    backlogItems: [
      {
        id: "bl-006",
        title: "Handle duplicate reference numbers",
        status: "DONE",
        jiraId: "VF-91",
      },
      { id: "bl-007", title: "Support XLSX in addition to CSV", status: "TODO" },
      { id: "bl-008", title: "Progress bar for large files", status: "TODO" },
    ],
    jiraSyncedIds: ["VF-91"],
  },
  {
    id: "session-004",
    title: "Webhook Integration — event log + retry UI",
    date: "2024-03-25",
    duration: 60,
    status: "CLOSED" as const,
    goal: "Prototype the webhook event log viewer and test with local ngrok tunnel to simulate real carrier tracking events.",
    linkedFeatureIds: ["feat-006"],
    promptIds: ["prompt-006"],
    notes: {
      worked:
        "Bolt produced a clean dark terminal aesthetic that matched the design brief well. Event filtering worked immediately.",
      improve:
        "Bolt doesn't handle real-time updates well — had to switch to polling every 3s. Consider using SWR with revalidateOnFocus for this pattern.",
    },
    backlogItems: [
      {
        id: "bl-009",
        title: "Add webhook signature verification",
        status: "IN_PROGRESS",
        jiraId: "VF-109",
      },
      {
        id: "bl-010",
        title: "Event payload diff viewer for retries",
        status: "TODO",
      },
    ],
    jiraSyncedIds: ["VF-109"],
  },
  {
    id: "session-005",
    title: "Spot Quote RFQ — email workflow MVP",
    date: "2024-04-02",
    duration: 180,
    status: "CLOSED" as const,
    goal: "Build the spot quote request workflow: multi-carrier selector, shipment detail form, auto-generate RFQ email draft, send via SendGrid.",
    linkedFeatureIds: ["feat-011"],
    promptIds: ["prompt-001", "prompt-008"],
    notes: {
      worked:
        "Claude generated the HTML email template on the first attempt with proper table formatting and responsive design. PM team loved the output.",
      improve:
        "The form had too many fields — users dropped off at step 2 in usability testing. Need to move optional fields behind an 'Advanced' toggle.",
    },
    backlogItems: [
      {
        id: "bl-011",
        title: "Add response deadline field to RFQ",
        status: "DONE",
        jiraId: "VF-114",
      },
      {
        id: "bl-012",
        title: "Carrier response inbox — collect replies",
        status: "TODO",
      },
      {
        id: "bl-013",
        title: "Compare responses side-by-side",
        status: "TODO",
      },
    ],
    jiraSyncedIds: ["VF-114"],
  },
  {
    id: "session-006",
    title: "Lane Performance Dashboard — charts sprint",
    date: "2024-04-08",
    duration: 240,
    status: "CLOSED" as const,
    goal: "Build the full lane performance dashboard including multi-series trend charts, carrier comparison table, and lane selector. Get to clickable prototype by end of session.",
    linkedFeatureIds: ["feat-009"],
    promptIds: ["prompt-003"],
    prototypeUrl: "https://prototype.vibeflow.app/lane-perf-v2",
    notes: {
      worked:
        "Recharts multi-series line chart looked excellent with custom tooltip. The 95% OTD reference line added a lot of visual clarity for stakeholders.",
      improve:
        "Date range picker took too long to style consistently. Should pull in a shadcn calendar component earlier in the session rather than building custom.",
    },
    backlogItems: [
      {
        id: "bl-014",
        title: "Drill-down to individual shipment list",
        status: "TODO",
      },
      {
        id: "bl-015",
        title: "Export chart as PNG",
        status: "TODO",
      },
      {
        id: "bl-016",
        title: "Carrier benchmark overlays",
        status: "IN_PROGRESS",
        jiraId: "VF-120",
      },
    ],
    jiraSyncedIds: ["VF-120"],
  },
];
